export const GET_CHANNELS = 'GET_CHANNELS';
export const ADD_CHANNEL = 'ADD_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const SHOW_CHANNEL_WINDOW = 'SHOW_CHANNEL_WINDOW';
export const SEND_TEXT_MESSAGE = 'SEND_TEXT_MESSAGE';
